import numpy as np

bond_replacement_dict = {
    "=": "",
    "-": "",
    "~": "",
    "#": "",
    ":": "",
    "$": "",
    "/": "",
    "\\": "",
    "@":"",
}

atom_replacement_dict = {
   "[Ag+]": "Ag",
    "[Ag+2]": "Ag",
    "[Au+]": "Au",
    "[Au+2]": "Au",
    "[Au+3]": "Au",
    "[Cd+]": "Cd",
    "[Cd+2]": "Cd",
    "[Co+]": "Co",
    "[Co+2]": "Co",
    "[Co+3]": "Co",
    "[Co]": "Co",
    "[Cr+2]": "Cr",
    "[Cr+3]": "Cr",
    "[Cr+4]": "Cr",
    "[Cr]": "Cr",
    "[Cu+]": "Cu",
    "[Cu+2]": "Cu",
    "[Cu+3]": "Cu",
    "[Fe+]": "Fe",
    "[Fe+2]": "Fe",
    "[Fe+3]": "Fe",
    "[Fe+7]" : "Fe",
    "[Fe]": "Fe",
    "[Hf+4]": "Hf",
    "[Hg+2]": "Hg",
    "[Hg+3]": "Hg",
    "[Ir+]": "Ir",
    "[Ir+2]": "Ir",
    "[Ir+3]": "Ir",
    "[Ir+4]": "Ir",
    "[Ir+5]": "Ir",
    "[Mn+]": "Mn",
    "[Mn+2]": "Mn",
    "[Mn+3]": "Mn",
    "[Mn+4]": "Mn",
    "[Mo+2]": "Mo",
    "[Mo+3]": "Mo",
    "[Mo+4]": "Mo",
    "[Mo+5]": "Mo",
    "[Mo+6]": "Mo",
    "[Mo]": "Mo",
    "[Nb+3]": "Nb",
    "[Nb+4]": "Nb",
    "[Nb+5]": "Nb",
    "[Ni+]": "Ni",
    "[Ni+2]": "Ni",
    "[Ni+3]": "Ni",
    "[Os+2]": "Os",
    "[Os+3]": "Os",
    "[Os+4]": "Os",
    "[Os+5]": "Os",
    "[Os]": "Os",
    "[Pd+2]": "Pd",
    "[Pd]": "Pd",
    "[Pt+]": "Pt",
    "[Pt+2]": "Pt",
    "[Pt+3]": "Pt",
    "[Pt+4]": "Pt",
    "[Pt]": "Pt",
    "[Re+]": "Re",
    "[Re+2]": "Re",
    "[Re+3]": "Re",
    "[Re+4]": "Re",
    "[Re+5]": "Re",
    "[Re+7]": "Re",
    "[Re]": "Re",
    "[Rh+]": "Rh",
    "[Rh+2]": "Rh",
    "[Rh+3]": "Rh",
    "[Rh+4]": "Rh",
    "[Ru+]": "Ru",
    "[Ru+2]": "Ru",
    "[Ru+3]": "Ru",
    "[Ru+4]": "Ru",
    "[Ru]": "Ru",
    "[Sc+3]": "Sc",
    "[Ta+3]": "Ta",
    "[Ta+4]": "Ta",
    "[Ta+5]": "Ta",
    "[Tc+]": "Tc",
    "[Tc+2]": "Tc",
    "[Tc+3]": "Tc",
    "[Tc+4]": "Tc",
    "[Ti+2]": "Ti",
    "[Ti+3]": "Ti",
    "[Ti+4]": "Ti",
    "[V+]": "V",
    "[V+2]": "V",
    "[V+3]": "V",
    "[V+4]": "V",
    "[W+2]": "W",
    "[W+3]": "W",
    "[W+4]": "W",
    "[W+5]": "W",
    "[W+6]": "W",
    "[W]": "W",
    "[Y+3]": "Y",
    "[Zn+2]": "Zn",
    "[Zr+2]": "Zr",
    "[Zr+3]": "Zr",
    "[Zr+4]": "Zr",
    "[CH]": "C",
    "[CH2]": "C",
    "[NH]": "N",
    "[NH2]": "N",
    "[NH3]": "N",
    "[BH]": "B",
    "[C]": "C",
    "[O]": "O",
    "[B]": "B",
    "[N]": "N",
    "[H]": "H",
    "[O+]": "O",
    "[O-]": "O",
    "[N+]": "N",
    "[N-]": "N",
    "[S+]": "S",
    "[S-]": "S",
    "[P+]": "P",
    "[P-]": "P",
    "[C+]": "C",
    "[C-]": "C",
    "[B+]": "B",
    "[B-]": "B",
    "[Cl]" : "Cl",
    "[SH]" : "S",
    "[CH3]" : "C",
    "[PH2]" : "P",
    "[OH]" : "O",

}
# function to clean up dict to simplify SMILES

def simplify_smiles(dictionary):
    
    cleaned_dictionary = {}
    for key in dictionary:
        new_key = key
        for bond in bond_replacement_dict:
            new_key = new_key.replace(bond, bond_replacement_dict[bond])
        for atom in atom_replacement_dict:
            new_key = new_key.replace(atom, atom_replacement_dict[atom])
        if new_key not in cleaned_dictionary:
            cleaned_dictionary[new_key] = np.array([])

        cleaned_dictionary[new_key] = np.append(cleaned_dictionary[new_key], dictionary[key])
    return cleaned_dictionary
